### ISSUE TITLE
Vertical Scrollbar when Printing the Receipt

### ISSUE THREAD

**Issue by code2be** [kilbot/WooCommerce-POS#17]
I have got a Vertical Scrollbar while trying to print the receipt. Which cause long paper to be printed ( using Receipt Thermal Printer ).

Fix was simple to set CSS:

``` CSS
html, body, .fade.in {
overflow: hidden !important;
}
```
